create extension if not exists pgcrypto;
create table public.beans(id uuid primary key default gen_random_uuid(),name text not null,roaster text not null,origin text not null default '',process text not null default '',roast text not null default '' check(roast in ('','Light','Medium-Light','Medium','Medium-Dark','Dark')),rating text not null default '' check(rating in ('','DISLIKE','LIKE','LOVE')),status text not null default 'ACTIVE' check(status in ('ACTIVE','ARCHIVED')),notes text[] not null default '{}',cover text not null default '',created_at timestamptz not null default now());
create table public.choices(id uuid primary key default gen_random_uuid(),kind text not null check(kind in ('note','process','pattern')),name text not null,category text not null default '',created_at timestamptz not null default now(),unique(kind,name));
create table public.equipment(id uuid primary key default gen_random_uuid(),kind text not null check(kind in ('grinder','dripper','filter','moka','sweetener')),name text not null,setting_type text not null default 'CLICKS' check(setting_type in ('CLICKS','NUMBER','CUSTOM_TEXT')),available boolean not null default true,is_default boolean not null default false,created_at timestamptz not null default now());
alter table public.choices add constraint note_has_category check(kind<>'note' or category in ('Fruity','Floral','Sweet','Chocolate / Nutty','Other'));
create unique index one_default_per_kind on public.equipment(kind) where is_default;
create table public.purchases(id uuid primary key default gen_random_uuid(),bean_id uuid not null references public.beans on delete cascade,date date not null default current_date,weight numeric not null check(weight>0),price numeric not null check(price>=0),created_at timestamptz not null default now());
create table public.recipe_versions(id uuid primary key default gen_random_uuid(),bean_id uuid not null references public.beans on delete cascade,family text not null check(family in ('AMERICANO_15','AMERICANO_20','HOT_LATTE','ICED_LATTE')),snapshot jsonb not null,created_at timestamptz not null default now(),unique(id,bean_id,family));
create table public.recipe_families(id uuid primary key default gen_random_uuid(),bean_id uuid not null references public.beans on delete cascade,family text not null,latest_id uuid not null,created_at timestamptz not null default now(),unique(bean_id,family),foreign key(latest_id,bean_id,family) references public.recipe_versions(id,bean_id,family) on delete cascade);
alter table public.recipe_versions add constraint snapshot_matches_family check(
  (family='AMERICANO_15' and snapshot->>'drink'='AMERICANO' and (snapshot->>'dose')::numeric=15) or
  (family='AMERICANO_20' and snapshot->>'drink'='AMERICANO' and (snapshot->>'dose')::numeric=20) or
  (family in ('HOT_LATTE','ICED_LATTE') and snapshot->>'drink'=family));
create table public.recipe_pins(id uuid primary key default gen_random_uuid(),bean_id uuid not null references public.beans on delete cascade,family text not null,label text not null,version_id uuid not null,created_at timestamptz not null default now(),unique(bean_id,family,label),foreign key(version_id,bean_id,family) references public.recipe_versions(id,bean_id,family) on delete cascade);
create table public.brew_logs(id uuid primary key default gen_random_uuid(),bean_id uuid not null references public.beans on delete cascade,family text not null check(family in ('AMERICANO_15','AMERICANO_20','AMERICANO_CUSTOM','HOT_LATTE','ICED_LATTE')),source_version_id uuid references public.recipe_versions on delete set null,snapshot jsonb not null,rating integer check(rating between 1 and 5),feedback text[] not null default '{}',note text not null default '',adjustments jsonb not null default '[]',created_at timestamptz not null default now());
create table public.taste_note_categories(id uuid primary key default gen_random_uuid(),name text not null unique,created_at timestamptz not null default now());
insert into public.taste_note_categories(name) values('Fruity'),('Floral'),('Sweet'),('Chocolate / Nutty'),('Other');
create table public.bean_taste_notes(bean_id uuid references public.beans on delete cascade,note_id uuid references public.choices on delete restrict,created_at timestamptz not null default now(),primary key(bean_id,note_id));
create table public.pour_steps(id uuid primary key default gen_random_uuid(),version_id uuid not null references public.recipe_versions on delete cascade,sort_order integer not null,start_time numeric not null,cumulative_water numeric not null,temperature numeric not null,patterns text[] not null,created_at timestamptz not null default now(),unique(version_id,sort_order));
create table public.brew_log_pour_steps(id uuid primary key default gen_random_uuid(),brew_id uuid not null references public.brew_logs on delete cascade,sort_order integer not null,start_time numeric not null,cumulative_water numeric not null,temperature numeric not null,patterns text[] not null,created_at timestamptz not null default now(),unique(brew_id,sort_order));
create table public.brew_feedback(id uuid primary key default gen_random_uuid(),brew_id uuid not null references public.brew_logs on delete cascade,feedback text not null,created_at timestamptz not null default now());
create table public.brew_adjustments(id uuid primary key default gen_random_uuid(),brew_id uuid not null references public.brew_logs on delete cascade,field text not null,delta numeric not null,label text not null,created_at timestamptz not null default now());
create function public.sync_bean_notes() returns trigger language plpgsql set search_path=public as $$declare n text;begin delete from bean_taste_notes where bean_id=new.id;foreach n in array new.notes loop insert into choices(kind,name,category) values('note',n,'Other') on conflict(kind,name) do nothing;insert into bean_taste_notes(bean_id,note_id) select new.id,id from choices where kind='note' and name=n on conflict do nothing;end loop;return new;end;$$;
create trigger bean_notes after insert or update of notes on public.beans for each row execute function public.sync_bean_notes();
create function public.sync_recipe_steps() returns trigger language plpgsql set search_path=public as $$begin insert into pour_steps(version_id,sort_order,start_time,cumulative_water,temperature,patterns) select new.id,ord::integer,(s->>'time')::numeric,(s->>'water')::numeric,(s->>'temperature')::numeric,array(select jsonb_array_elements_text(s->'patterns')) from jsonb_array_elements(new.snapshot->'steps') with ordinality as a(s,ord);return new;end;$$;
create trigger recipe_steps after insert on public.recipe_versions for each row execute function public.sync_recipe_steps();
create function public.sync_brew_details() returns trigger language plpgsql set search_path=public as $$begin delete from brew_log_pour_steps where brew_id=new.id;delete from brew_feedback where brew_id=new.id;delete from brew_adjustments where brew_id=new.id;insert into brew_log_pour_steps(brew_id,sort_order,start_time,cumulative_water,temperature,patterns) select new.id,ord::integer,(s->>'time')::numeric,(s->>'water')::numeric,(s->>'temperature')::numeric,array(select jsonb_array_elements_text(s->'patterns')) from jsonb_array_elements(new.snapshot->'steps') with ordinality as a(s,ord);insert into brew_feedback(brew_id,feedback) select new.id,unnest(new.feedback);insert into brew_adjustments(brew_id,field,delta,label) select new.id,a->>'field',(a->>'delta')::numeric,a->>'label' from jsonb_array_elements(new.adjustments) a;return new;end;$$;
create trigger brew_details after insert or update on public.brew_logs for each row execute function public.sync_brew_details();
create index brew_bean_date on public.brew_logs(bean_id,created_at desc);
create index versions_bean on public.recipe_versions(bean_id,family);
create index purchases_bean on public.purchases(bean_id,date desc);
create table public.app_sessions(token_hash text primary key,created_at timestamptz not null default now());
create table public.pin_attempts(key_hash text primary key,attempts integer not null default 0,window_start timestamptz not null default now());
create function public.allow_pin_attempt(key_hash text) returns boolean language plpgsql set search_path=public as $$
declare n integer; begin insert into pin_attempts as p(key_hash,attempts) values(key_hash,1) on conflict on constraint pin_attempts_pkey do update set attempts=case when p.window_start < now()-interval '15 minutes' then 1 else p.attempts+1 end,window_start=case when p.window_start < now()-interval '15 minutes' then now() else p.window_start end returning attempts into n;return n<=5;end;$$;
create function public.save_recipe(p_bean uuid,p_family text,p_snapshot jsonb) returns uuid language plpgsql set search_path=public as $$
declare v uuid;begin insert into recipe_versions(bean_id,family,snapshot) values(p_bean,p_family,p_snapshot) returning id into v;insert into recipe_families(bean_id,family,latest_id) values(p_bean,p_family,v) on conflict(bean_id,family) do update set latest_id=excluded.latest_id;return v;end;$$;
create function public.buy_again(p_bean uuid,p_date date,p_weight numeric,p_price numeric) returns void language plpgsql set search_path=public as $$begin insert into purchases(bean_id,date,weight,price) values(p_bean,p_date,p_weight,p_price);update beans set status='ACTIVE' where id=p_bean;end;$$;
create function public.save_next_recipe(p_brew uuid,p_snapshot jsonb,p_adjustments jsonb) returns uuid language plpgsql set search_path=public as $$declare b brew_logs;v uuid;begin select * into strict b from brew_logs where id=p_brew for update;if b.family='AMERICANO_CUSTOM' then raise exception 'Custom dose feedback cannot update Latest';end if;v:=save_recipe(b.bean_id,b.family,p_snapshot);update brew_logs set adjustments=p_adjustments where id=p_brew;return v;end;$$;
create function public.save_equipment(p_id uuid,p_value jsonb) returns void language plpgsql set search_path=public as $$begin perform pg_advisory_xact_lock(72841);if (p_value->>'is_default')::boolean then update equipment set is_default=false where kind=p_value->>'kind';end if;if p_id is null then insert into equipment(name,kind,setting_type,available,is_default) values(p_value->>'name',p_value->>'kind',p_value->>'setting_type',(p_value->>'available')::boolean,(p_value->>'is_default')::boolean);else update equipment set name=p_value->>'name',kind=p_value->>'kind',setting_type=p_value->>'setting_type',available=(p_value->>'available')::boolean,is_default=(p_value->>'is_default')::boolean where id=p_id;end if;end;$$;
create function public.reject_version_update() returns trigger language plpgsql as $$begin raise exception 'Recipe versions are immutable';end;$$;
create trigger immutable_version before update on public.recipe_versions for each row execute function public.reject_version_update();
do $$declare t text;begin foreach t in array array['beans','choices','equipment','purchases','recipe_versions','recipe_families','recipe_pins','brew_logs','app_sessions','pin_attempts','taste_note_categories','bean_taste_notes','pour_steps','brew_log_pour_steps','brew_feedback','brew_adjustments'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon, authenticated',t);end loop;end;$$;
revoke execute on function public.allow_pin_attempt(text),public.save_recipe(uuid,text,jsonb),public.save_next_recipe(uuid,jsonb,jsonb),public.buy_again(uuid,date,numeric,numeric),public.save_equipment(uuid,jsonb) from public,anon,authenticated;
grant execute on function public.allow_pin_attempt(text),public.save_recipe(uuid,text,jsonb),public.save_next_recipe(uuid,jsonb,jsonb),public.buy_again(uuid,date,numeric,numeric),public.save_equipment(uuid,jsonb) to service_role;
grant all on all tables in schema public to service_role;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('bean-covers','bean-covers',false,12582912,array['image/webp']) on conflict(id) do nothing;
